### ISSUE TITLE
neotest doesn't recognise tests with hspec? 

### ISSUE THREAD

**Issue by MangoIV** [mrcjkb/neotest-haskell#100]
### Question

![image](https://github.com/mrcjkb/neotest-haskell/assets/40720523/e7697442-a27f-46c1-9ce4-33ae708430e9)

for some reason, it tells me "no tests found" 

What do I have to do such that it works?

**Comment by mrcjkb** [comment]
Hey,
thanks for reporting this.
This is likely because of the default implementation of [`NeotestAdapter.is_test_file`](https://github.com/mrcjkb/neotest-haskell/blob/5c7adf30453abd9cc7235bae4da319b905051b81/lua/neotest-haskell/base.lua#L6).

```lua
function(file_path)
  if not vim.endswith(file_path, '.hs') then
    return false
  end
  return vim.endswith(file_path, 'Spec.hs') or vim.endswith(file_path, 'Test.hs') or vim.endswith(file_path, 'Tests.hs')
end
```

It would probably make sense to add checks for a `spec` or `test` parent directory.

The function can also be overridden in the setup:

```lua
require('neotest').setup {
  is_test_file = function(file_path)
    -- ...
  end,
}
```

**Comment by mrcjkb** [comment]
@all-contributors please add @MangoIV  for bug

**Comment by MangoIV** [comment]
Awesome, you're the best <3
